export const SIGN_USER = 'SIGN_USER';
export const AUTORIZE_USER = 'AUTORIZE_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const CHANGE_USER_SECOND_NAME = 'CHANGE_USER_SECOND_NAME';
export const CHANGE_USER_EMAIL = 'CHANGE_USER_EMAIL';
export const CHANGE_USER_LOGIN = 'CHANGE_USER_LOGIN';
export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';
